import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>O.T.E. Exotic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
    <h1 style={{"text-align":"center"}}>
        <u>
            <p style={{"font-size": "55px", "font-family":"Helvetica", "color":"#00a3cc"}}>O.T.E. EXOTIC CO.</p>
        </u>
    </h1>

    <h5 style={{"text-align":"center"}}>
        <p style={{"font-size": "20px", "color":"#000000", "font-family": "Helvetica"}}>
            Wholesale Birds, Cages and Accessories
        </p>
    </h5> 

    <hr/>
    <h4 style={{"text-align":"center", "font-family":"Helvetica"}}>
    <ul><li><a href="/">Home</a></li>
    <li><a href="/catalog">Catalog</a></li>
    <li><a href="/contact">Contact Information</a></li>
    </ul>
    </h4>

    <hr/>

    <p><h3 style={{"color":"#00a3cc", "font-size":"25px", "font-family":"helvetica"}}><u>Catalog</u></h3><h5 style={{"color":"#00a3cc", "font-size":"14", "font-family":"helvetica"}}>Want a closer look? Try clicking the pictures!</h5></p>
    <p><h5 style={{"color":"#00a3cc", "font-family":"helvetica", "font-size":"14"}}>(Some Items have multiple colors! Please contact Oscar if you have any questions!)</h5></p>
    <p><h5 style={{"color":"#00a3cc", "font-size":"20px", "font-family":"Helvetica"}}><u>Feeders:</u></h5></p>

    <table>
        <tr style={{"margin-left": "auto", "margin-right":"auto"}}>
        <td><a href="https://i.redd.it/f3kb28p5cb671.png"><img src="https://i.redd.it/f3kb28p5cb671.png" alt="Item  #8001"style={{"width":"60px", "height":"80px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8001</p></h5></p></td>
        <td><a href="https://i.redd.it/jo8gjcfbeb671.png"><img src="https://i.redd.it/jo8gjcfbeb671.png" alt="Item  #8002"style={{"width":"60px", "height":"80px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8002</p></h5></p></td>
        <td><a href="https://i.redd.it/gtmzl7bveb671.png"><img src="https://i.redd.it/gtmzl7bveb671.png" alt="Item  #8003"style={{"width":"70px", "height":"80px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8003</p></h5></p></td>
        <td><a href="https://i.redd.it/putk5jjkkb671.png"><img src="https://i.redd.it/putk5jjkkb671.png" alt="Item  #8004"style={{"width":"65px", "height":"80px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8004</p></h5></p></td>
        <td><a href="https://i.redd.it/8aq2s25vkb671.png"><img src="https://i.redd.it/8aq2s25vkb671.png" alt="Item  #8005"style={{"width":"65px", "height":"80px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8005</p></h5></p></td>
        <td><a href="https://i.redd.it/rky08zt8lb671.png"><img src="https://i.redd.it/rky08zt8lb671.png" alt="Item  #8006"style={{"width":"60px", "height":"80px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8006</p></h5></p></td>
        <td><a href="https://i.redd.it/nub6iu1llb671.png"><img src="https://i.redd.it/nub6iu1llb671.png" alt="Item  #8007"style={{"width":"60px", "height":"80px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8007</p></h5></p></td>
        <td><a href="https://i.redd.it/pqcvk0wwlb671.png"><img src="https://i.redd.it/pqcvk0wwlb671.png" alt="Item  #8021"style={{"width":"50px", "height":"80px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8021</p></h5></p></td>
        <td><a href="https://i.redd.it/81308ujfmb671.png"><img src="https://i.redd.it/81308ujfmb671.png" alt="Item  #8022"style={{"width":"55px", "height":"80px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8022</p></h5></p></td>
        <td><a href="https://i.redd.it/17vfpq8wmb671.png"><img src="https://i.redd.it/17vfpq8wmb671.png" alt="Item  #8023"style={{"width":"70px", "height":"60px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8023</p></h5></p></td>
        <td><a href="https://i.redd.it/zlxfqpcanb671.png"><img src="https://i.redd.it/zlxfqpcanb671.png" alt="Item  #8031"style={{"width":"55px", "height":"50px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8031</p></h5></p></td>
        <td><a href="https://i.redd.it/ij5dt3drnb671.png"><img src="https://i.redd.it/ij5dt3drnb671.png" alt="Item  #8031"style={{"width":"60px", "height":"65px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8032</p></h5></p></td>
        <td><a href="https://i.redd.it/qtsec98job671.png"><img src="https://i.redd.it/qtsec98job671.png" alt="Item  #8033"style={{"width":"60px", "height":"70px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8033</p></h5></p></td>
        <td><a href="https://i.redd.it/yk3lyrcepb671.png"><img src="https://i.redd.it/yk3lyrcepb671.png" alt="Item  #8035"style={{"width":"60px", "height":"70px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8035</p></h5></p></td>
        <td><a href="https://i.redd.it/fkoqta0dqb671.png"><img src="https://i.redd.it/fkoqta0dqb671.png" alt="Item  #8036"style={{"width":"60px", "height":"70px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8036</p></h5></p></td>
        <td><a href="https://i.redd.it/sjzs41pkqb671.png"><img src="https://i.redd.it/sjzs41pkqb671.png" alt="Item  #8037"style={{"width":"65px", "height":"70px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8037</p></h5></p></td>
        <td><a href="https://i.redd.it/h6nq1onfrb671.png"><img src="https://i.redd.it/h6nq1onfrb671.png" alt="Item  #8041"style={{"width":"55px", "height":"70px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8041</p></h5></p></td>
        <td><a href="https://i.redd.it/1e37o0csrb671.png"><img src="https://i.redd.it/1e37o0csrb671.png" alt="Item  #8050"style={{"width":"80px", "height":"70px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8050</p></h5></p></td>
        </tr>

        <tr>
        <td><a href="https://i.redd.it/l2iya6srtb671.png"><img src="https://i.redd.it/l2iya6srtb671.png" alt="Item  #8051"style={{"width":"55px", "height":"65px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8051</p></h5></p></td>
        <td><a href="https://i.redd.it/gbql1yym0c671.png"><img src="https://i.redd.it/gbql1yym0c671.png" alt="Item  #8052"style={{"width":"60px", "height":"70px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8052</p></h5></p></td>
        <td><a href="https://i.redd.it/iq7tfd9w0c671.png"><img src="https://i.redd.it/iq7tfd9w0c671.png" alt="Item  #8053"style={{"width":"60px", "height":"70px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8053</p></h5></p></td>
        <td><a href="https://i.redd.it/nn40ccef1c671.png"><img src="https://i.redd.it/nn40ccef1c671.png" alt="Item  #8053B"style={{"width":"60px", "height":"65px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8053B</p></h5></p></td>
        <td><a href="https://i.redd.it/7xcoaj172c671.png"><img src="https://i.redd.it/7xcoaj172c671.png" alt="Item  #8054"style={{"width":"60px", "height":"65px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8054</p></h5></p></td>
        <td><a href="https://i.redd.it/y4tdbqna3c671.png"><img src="https://i.redd.it/y4tdbqna3c671.png" alt="Item  #8055"style={{"width":"50px", "height":"45px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8055</p></h5></p></td>
        <td><a href="https://i.redd.it/ihpdn1wn3c671.png"><img src="https://i.redd.it/ihpdn1wn3c671.png" alt="Item  #8058"style={{"width":"60px", "height":"55px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8058</p></h5></p></td>
        <td><a href="https://i.redd.it/490xzao74c671.png"><img src="https://i.redd.it/490xzao74c671.png" alt="Item  #8059"style={{"width":"55px", "height":"50px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8059</p></h5></p></td>
        <td><a href="https://i.redd.it/sucsbypo4c671.png"><img src="https://i.redd.it/sucsbypo4c671.png" alt="Item  #8061"style={{"width":"55px", "height":"65px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8061</p></h5></p></td>
        <td><a href="https://i.redd.it/6aubdwmk5c671.png"><img src="https://i.redd.it/6aubdwmk5c671.png" alt="Item  #8063"style={{"width":"65px", "height":"65px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8063</p></h5></p></td>
        <td><a href="https://i.redd.it/rxjkauxe7c671.png"><img src="https://i.redd.it/rxjkauxe7c671.png" alt="Item  #8097"style={{"width":"50px", "height":"70px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8097</p></h5></p></td>
        <td><a href="https://i.redd.it/rxjkauxe7c671.png"><img src="https://i.redd.it/rxjkauxe7c671.png" alt="Item  #8098"style={{"width":"60px", "height":"75px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8098</p></h5></p></td>
        <td><a href="https://i.redd.it/a3ofabf5ai671.png"><img src="https://i.redd.it/a3ofabf5ai671.png" alt="Item  #8062"style={{"width":"60px", "height":"60px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8062</p></h5></p></td>
        <td><a href="https://i.redd.it/foelruqjai671.png"><img src="https://i.redd.it/foelruqjai671.png" alt="Item  #8064"style={{"width":"60px", "height":"60px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8064</p></h5></p></td>
        <td><a href="https://i.redd.it/e7m3l8ixai671.png"><img src="https://i.redd.it/e7m3l8ixai671.png" alt="Item  #8065"style={{"width":"60px", "height":"60px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8065</p></h5></p></td>
        <td><a href="https://i.redd.it/rnq0be67bi671.png"><img src="https://i.redd.it/rnq0be67bi671.png" alt="Item  #8066"style={{"width":"65px", "height":"65px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8066</p></h5></p></td>
        <td><a href="https://i.redd.it/8by617vnbi671.png"><img src="https://i.redd.it/8by617vnbi671.png" alt="Item  #8067"style={{"width":"65px", "height":"65px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8067</p></h5></p></td>
        <td><a href="https://i.redd.it/xnk14zo0ci671.png"><img src="https://i.redd.it/xnk14zo0ci671.png" alt="Item  #8068"style={{"width":"60px", "height":"60px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8068</p></h5></p></td>
        </tr>
    </table>

    <table>
        <tr>
        <td><a href="https://i.redd.it/0gwfl73gdi671.png"><img src="https://i.redd.it/0gwfl73gdi671.png" alt="Item  #8081"style={{"width":"40px", "height":"70px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8081</p></h5></p></td>
        <td><a href="https://i.redd.it/4k2x2n7udi671.png"><img src="https://i.redd.it/4k2x2n7udi671.png" alt="Item  #8082"style={{"width":"40px", "height":"70px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8082</p></h5></p></td>
        <td><a href="https://i.redd.it/13nxw6lmei671.png"><img src="https://i.redd.it/13nxw6lmei671.png" alt="Item  #8084"style={{"width":"35px", "height":"65px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8084</p></h5></p></td>
        <td><a href="https://i.redd.it/c6mkder6fi671.png"><img src="https://i.redd.it/c6mkder6fi671.png" alt="Item  #8085"style={{"width":"25px", "height":"80px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8085</p></h5></p></td>
        <td><a href="https://i.redd.it/ym00qzctqb671.png"><img src="https://i.redd.it/ym00qzctqb671.png" alt="Item  #8038"style={{"width":"120px", "height":"70px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8038</p></h5></p></td>
        <td><a href="https://i.redd.it/5vtmd2bsoi671.png"><img src="https://i.redd.it/5vtmd2bsoi671.png" alt="Item  #00162"style={{"width":"60px", "height":"70px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#00162</p></h5></p></td>
        <td><a href="https://i.redd.it/gx8vy8k2pi671.png"><img src="https://i.redd.it/gx8vy8k2pi671.png" alt="Item  #00119"style={{"width":"70px", "height":"80px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#00119</p></h5></p></td>
        <td><a href="https://i.redd.it/slbsg8c8pi671.png"><img src="https://i.redd.it/slbsg8c8pi671.png" alt="Item  #00112"style={{"width":"60px", "height":"70px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#00112</p></h5></p></td>
        <td><a href="https://i.redd.it/mrjop2lepi671.png"><img src="https://i.redd.it/mrjop2lepi671.png" alt="Item  #00127"style={{"width":"60px", "height":"70px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#00127</p></h5></p></td>
        </tr>
    </table>

    <hr/>

    <p><h5 style={{"color":"#00a3cc", "font-size":"20px", "font-family":"Helvetica"}}><u>Toys and Accessories:</u></h5></p>

    <table>
        <tr>
        <td><a href="https://i.redd.it/p0lyupuymp671.png"><img src="https://i.redd.it/p0lyupuymp671.png" alt="Item  #8331"style={{"width":"40px", "height":"60px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8331</p></h5></p></td>
        <td><a href="https://i.redd.it/3ulmhhrznp671.png"><img src="https://i.redd.it/3ulmhhrznp671.png" alt="Item  #8334"style={{"width":"65px", "height":"70px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8334</p></h5></p></td>
        <td><a href="https://i.redd.it/axgenk0fop671.png"><img src="https://i.redd.it/axgenk0fop671.png" alt="Item  #8336"style={{"width":"35px", "height":"85px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8336</p></h5></p></td>
        <td><a href="https://i.redd.it/osvmjm11pp671.png"><img src="https://i.redd.it/osvmjm11pp671.png" alt="Item  #8338"style={{"width":"40px", "height":"90px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8338</p></h5></p></td>
        <td><a href="https://i.redd.it/ezwdjp7jpp671.png"><img src="https://i.redd.it/ezwdjp7jpp671.png" alt="Item  #8399"style={{"width":"60px", "height":"70px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8399</p></h5></p></td>
        <td><a href="https://i.redd.it/iks4lty3qp671.png"><img src="https://i.redd.it/iks4lty3qp671.png" alt="Item  #8095"style={{"width":"60px", "height":"70px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8095</p></h5></p></td>
        <td><a href="https://i.redd.it/siupinw2rp671.png"><img src="https://i.redd.it/siupinw2rp671.png" alt="Item  #8091"style={{"width":"45px", "height":"70px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8091</p></h5></p></td>
        <td><a href="https://i.redd.it/64uagf9asp671.png"><img src="https://i.redd.it/64uagf9asp671.png" alt="Item  #8201"style={{"width":"60px", "height":"70px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8201</p></h5></p></td>
        <td><a href="https://i.redd.it/ldmdxhhv3w671.png"><img src="https://i.redd.it/ldmdxhhv3w671.png" alt="Item  #8611"style={{"width":"65px", "height":"70px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8611</p></h5></p></td>
        <td><a href="https://i.redd.it/9jd5s6s3tp671.png"><img src="https://i.redd.it/9jd5s6s3tp671.png" alt="Item  #8613"style={{"width":"65px", "height":"70px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8613</p></h5></p></td>
        <td><a href="https://i.redd.it/9r8qsinz9w671.png"><img src="https://i.redd.it/9r8qsinz9w671.png" alt="Item  #8614"style={{"width":"55px", "height":"60px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8614</p></h5></p></td>
        <td><a href="https://i.redd.it/yohib3qabw671.png"><img src="https://i.redd.it/yohib3qabw671.png" alt="Item  #8615"style={{"width":"60px", "height":"70px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8615</p></h5></p></td>
        <td><a href="https://i.redd.it/maii13dccw671.png"><img src="https://i.redd.it/maii13dccw671.png" alt="Item  #8618"style={{"width":"70px", "height":"80px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8618</p></h5></p></td>
        <td><a href="https://i.redd.it/x0fj1a836a771.png"><img src="https://i.redd.it/x0fj1a836a771.png" alt="Item  #8502"style={{"width":"38px", "height":"45px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8502</p></h5></p></td>
        <td><a href="https://i.redd.it/l197u0zh6a771.png"><img src="https://i.redd.it/l197u0zh6a771.png" alt="Item  #8504"style={{"width":"50px", "height":"70px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8504</p></h5></p></td>
        <td><a href="https://i.redd.it/s6ag7rkj7a771.png"><img src="https://i.redd.it/s6ag7rkj7a771.png" alt="Item  #8506"style={{"width":"65px", "height":"80px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8506</p></h5></p></td>
        <td><a href="https://i.redd.it/2gnp2pxjka771.png"><img src="https://i.redd.it/2gnp2pxjka771.png" alt="Item  #8451"style={{"width":"40px", "height":"45px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8451</p></h5></p></td>
        <td><a href="https://i.redd.it/l76cwsj28a771.png"><img src="https://i.redd.it/l76cwsj28a771.png" alt="Item  #8452"style={{"width":"40px", "height":"55px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8452</p></h5></p></td>
        <td><a href="https://i.redd.it/l76cwsj28a771.png"><img src="https://i.redd.it/l76cwsj28a771.png" alt="Item  #8452"style={{"width":"40px", "height":"55px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8452</p></h5></p></td>
        </tr>
    </table>

    <table>
        <tr>
        <td><a href="https://i.redd.it/d62is2j6dw671.png"><img src="https://i.redd.it/d62is2j6dw671.png" alt="Item  #8542; Item #8543"style={{"width":"120px", "height":"40px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "12px", "text-align":"center"}}><p><b>#8542</b>:9.5''  <b>#8543</b>:12''</p></h5></p></td>
        <td><a href="https://i.redd.it/8xjvbt6kew671.png"><img src="https://i.redd.it/8xjvbt6kew671.png" alt="Item  #8544; Item #8545"style={{"width":"152px", "height":"40px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p><b>#8544</b>:18''  <b>#8545</b>:24''</p></h5></p></td>
        <td><a href="https://i.redd.it/b8poqvqlkw671.png"><img src="https://i.redd.it/b8poqvqlkw671.png" alt="Item  #8564"style={{"width":"180px", "height":"42px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica" , "font-size": "14px", "text-align":"center"}}><p>#8564:18''</p></h5></p></td>
        <td><a href="https://i.redd.it/e1qdz6ajlw671.png"><img src="https://i.redd.it/e1qdz6ajlw671.png" alt="Item  #8565"style={{"width":"190px", "height":"42px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica" , "font-size": "14px", "text-align":"center"}}><p>#8565:24''</p></h5></p></td>
        <td><a href="https://i.redd.it/nh924huxgw671.png"><img src="https://i.redd.it/nh924huxgw671.png" alt="Item  #8546; Item #8547"style={{"width":"180px", "height":"40px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p><b>#8546</b>:36''  <b>#8547</b>:48''</p></h5></p></td>
        <td><a href="https://i.redd.it/6pttk913jw671.png"><img src="https://i.redd.it/6pttk913jw671.png" alt="Item  #8546; Item #8547"style={{"width":"180px", "height":"42px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p><b>#8566</b>:36''  <b>#8567</b>:48''</p></h5></p></td>
        </tr>
    </table>

    <table> 
        <tr>
        <td><a href="https://i.redd.it/zdvzq17lnw671.png"><img src="https://i.redd.it/zdvzq17lnw671.png" alt="Item  #8655; Item  #8654; Item #8653; Item  #8652; Item  #8651"style={{"width":"180px", "height":"80px"}}></img></a></td>
        <td>
        <h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "12px", "text-align": "center", "text-align":"left"}}>
        <p>#8651:Ø 6"×13"</p>
        <p>#8652:Ø 8"×20"</p>
        <p>#8653:Ø 9.5"×22"</p>
        <p>#8654:Ø 11"×29.5"</p>
        <p>#8655:Ø 11"×48"</p>
        </h5>
        </td>
        <td><a href="https://i.redd.it/si564l3qrw671.png"><img src="https://i.redd.it/si564l3qrw671.png" alt="Item  #8570"style={{"width":"80px", "height":"15px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8570:7"</p></h5></p></td>
        <td><a href="https://i.redd.it/jj3vc3q5tw671.png"><img src="https://i.redd.it/jj3vc3q5tw671.png" alt="Item  #8577"style={{"width":"120px", "height":"12px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8577:17"</p></h5></p></td>
        <td><a href="https://i.redd.it/jj3vc3q5tw671.png"><img src="https://i.redd.it/jj3vc3q5tw671.png" alt="Item  #8577"style={{"width":"129px", "height":"12px"}}></img></a><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8577:18"</p></h5></p></td>
        <td><a href="https://i.redd.it/xg2ovw38ww671.png"><img src="https://i.redd.it/xg2ovw38ww671.png" alt="Item #8571"style={{"width":"140px", "height":"12px"}}></img></a><p><h5 style={{"color": "#000000", "font-family":"helvetica", "font-size":"14px" ,"text-align":"center"}}><p>#8571: 24"</p></h5></p></td>
        <td><a href="https://i.redd.it/xg2ovw38ww671.png"><img src="https://i.redd.it/xg2ovw38ww671.png" alt="Item #8572"style={{"width":"145px", "height":"12px"}}></img></a><p><h5 style={{"color": "#000000", "font-family":"helvetica", "font-size":"14px" ,"text-align":"center"}}><p>#8572: 31"</p></h5></p></td>
        </tr>
    </table>

    <table>
        <tr>
        <td><a href="https://i.redd.it/020imbegyw671.png"><img src="https://i.redd.it/020imbegyw671.png" alt="Item #3062"style={{"width":"60px", "height":"90px"}}></img></a><p><h5 style={{"color": "#000000", "font-family":"helvetica", "font-size":"14px", "text-align":"center"}}><p>#3062</p></h5></p></td>
        <td><a href="https://i.redd.it/i1s62gn8zw671.png"><img src="https://i.redd.it/i1s62gn8zw671.png" alt="Item #3063"style={{"width":"60px", "height":"90px"}}></img></a><p><h5 style={{"color": "#000000", "font-family":"helvetica", "font-size":"14px", "text-align":"center"}}><p>#3063</p></h5></p></td>
        <td><a href="https://i.redd.it/du0ef0oszw671.png"><img src="https://i.redd.it/du0ef0oszw671.png" alt="Item #3063"style={{"width":"60px", "height":"90px"}}></img></a><p><h5 style={{"color": "#000000", "font-family":"helvetica", "font-size":"14px", "text-align":"center"}}><p>#3063</p></h5></p></td>
        <td><a href="https://i.redd.it/cwlz6ead0x671.png"><img src="https://i.redd.it/cwlz6ead0x671.png" alt="Item #3063"style={{"width":"60px", "height":"100px"}}></img></a><p><h5 style={{"color": "#000000", "font-family":"helvetica", "font-size":"14px", "text-align":"center"}}><p>#3063</p></h5></p></td>
        <td><a href="https://i.redd.it/45el9kwy0x671.png"><img src="https://i.redd.it/45el9kwy0x671.png" alt="Item #3066"style={{"width":"60px", "height":"100px"}}></img></a><p><h5 style={{"color": "#000000", "font-family":"helvetica", "font-size":"14px", "text-align":"center"}}><p>#3066</p></h5></p></td>
        <td><a href="https://i.redd.it/nsa0b7xz1x671.png"><img src="https://i.redd.it/nsa0b7xz1x671.png" alt="Item #3091"style={{"width":"45px", "height":"85px"}}></img></a><p><h5 style={{"color": "#000000", "font-family":"helvetica", "font-size":"14px", "text-align":"center"}}><p>#3091</p></h5></p></td>
        <td><a href="https://i.redd.it/duteacup5x671.png"><img src="https://i.redd.it/duteacup5x671.png" alt="Item #3091"style={{"width":"40px", "height":"110px"}}></img></a><p><h5 style={{"color": "#000000", "font-family":"helvetica", "font-size":"14px", "text-align":"center"}}><p>#3091</p></h5></p></td>
        <td><a href="https://i.redd.it/7zwc8egj6x671.png"><img src="https://i.redd.it/7zwc8egj6x671.png" alt="Item #3091"style={{"width":"40px", "height":"105px"}}></img></a><p><h5 style={{"color": "#000000", "font-family":"helvetica", "font-size":"14px", "text-align":"center"}}><p>#3091</p></h5></p></td>
        <td><a href="https://i.redd.it/e0o88k0q7x671.png"><img src="https://i.redd.it/e0o88k0q7x671.png" alt="Item #3096"style={{"width":"60px", "height":"70px"}}></img></a><p><h5 style={{"color": "#000000", "font-family":"helvetica", "font-size":"14px", "text-align":"center"}}><p>#3096</p></h5></p></td>
        <td><a href="https://i.redd.it/5lhvs0uuq3771.png"><img src="https://i.redd.it/5lhvs0uuq3771.png" alt="Item #3097"style={{"width":"45px", "height":"105px"}}></img></a><p><h5 style={{"color": "#000000", "font-family":"helvetica", "font-size":"14px", "text-align":"center"}}><p>#3097</p></h5></p></td>
        <td><a href="https://i.redd.it/imzd643hr3771.png"><img src="https://i.redd.it/imzd643hr3771.png" alt="Item #3098"style={{"width":"50px", "height":"105px"}}></img></a><p><h5 style={{"color": "#000000", "font-family":"helvetica", "font-size":"14px", "text-align":"center"}}><p>#3098</p></h5></p></td>
        <td><a href="https://i.redd.it/rxdzob76z3771.png"><img src="https://i.redd.it/rxdzob76z3771.png" alt="Item #3011"style={{"width":"70px", "height":"45px"}}></img></a><p><h5 style={{"color": "#000000", "font-family":"helvetica", "font-size":"14px" ,"text-align":"center"}}><p>#3011</p></h5></p></td>
        <td><a href="https://i.redd.it/ucd05dd0z3771.png"><img src="https://i.redd.it/ucd05dd0z3771.png" alt="Item #3012"style={{"width":"70px", "height":"50px"}}></img></a><p><h5 style={{"color": "#000000", "font-family":"helvetica", "font-size":"14px" ,"text-align":"center"}}><p>#3012</p></h5></p></td>
        <td><a href="https://i.redd.it/m0cwwmfkx3771.png"><img src="https://i.redd.it/m0cwwmfkx3771.png" alt="Item #3013"style={{"width":"75px", "height":"55px"}}></img></a><p><h5 style={{"color": "#000000", "font-family":"helvetica", "font-size":"14px" ,"text-align":"center"}}><p>#3013</p></h5></p></td>
        <td><a href="https://i.redd.it/luv6unc2x3771.png"><img src="https://i.redd.it/luv6unc2x3771.png" alt="Item #3014"style={{"width":"80px", "height":"60px"}}></img></a><p><h5 style={{"color": "#000000", "font-family":"helvetica", "font-size":"14px" ,"text-align":"center"}}><p>#3014</p></h5></p></td>
        <td><a href="https://i.redd.it/aiffgce404771.png"><img src="https://i.redd.it/aiffgce404771.png" alt="Item #3021"style={{"width":"55px", "height":"55px"}}></img></a><p><h5 style={{"color": "#000000", "font-family":"helvetica", "font-size":"14px" ,"text-align":"center"}}><p>#3021</p></h5></p></td>
        <td><a href="https://i.redd.it/tz5ejeze04771.png"><img src="https://i.redd.it/tz5ejeze04771.png" alt="Item #3022"style={{"width":"60px", "height":"60px"}}></img></a><p><h5 style={{"color": "#000000", "font-family":"helvetica", "font-size":"14px" ,"text-align":"center"}}><p>#3022</p></h5></p></td>
        <td><a href="https://i.redd.it/fo00fnwp04771.png"><img src="https://i.redd.it/fo00fnwp04771.png" alt="Item #3023"style={{"width":"65px", "height":"65px"}}></img></a><p><h5 style={{"color": "#000000", "font-family":"helvetica", "font-size":"14px" ,"text-align":"center"}}><p>#3023</p></h5></p></td>
        <td><a href="https://i.redd.it/ziycmq5024771.png"><img src="https://i.redd.it/ziycmq5024771.png" alt="Item #3024"style={{"width":"70px", "height":"70px"}}></img></a><p><h5 style={{"color": "#000000", "font-family":"helvetica", "font-size":"14px" ,"text-align":"center"}}><p>#3024</p></h5></p></td>
        </tr>
    </table>

    <table>
        <tr>
        <td><a href="https://i.redd.it/ltvrmv4f24771.png"><img src="https://i.redd.it/ltvrmv4f24771.png" alt="Item #3031"style={{"width":"55px", "height":"70px"}}></img></a><p><h5 style={{"color": "#000000", "font-family":"helvetica", "font-size":"14px", "text-align":"center"}}><p>#3031</p></h5></p></td>
        <td><a href="https://i.redd.it/8l3l30r984771.png"><img src="https://i.redd.it/8l3l30r984771.png" alt="Item #3036"style={{"width":"55px", "height":"70px"}}></img></a><p><h5 style={{"color": "#000000", "font-family":"helvetica", "font-size":"14px", "text-align":"center"}}><p>#3036</p></h5></p></td>
        <td><a href="https://i.redd.it/ub30cbpm84771.png"><img src="https://i.redd.it/ub30cbpm84771.png" alt="Item #3037"style={{"width":"55px", "height":"70px"}}></img></a><p><h5 style={{"color": "#000000", "font-family":"helvetica", "font-size":"14px", "text-align":"center"}}><p>#3037</p></h5></p></td>
        <td><a href="https://i.redd.it/in71mki194771.png"><img src="https://i.redd.it/in71mki194771.png" alt="Item #3038"style={{"width":"50px", "height":"75px"}}></img></a><p><h5 style={{"color": "#000000", "font-family":"helvetica", "font-size":"14px", "text-align":"center"}}><p>#3038</p></h5></p></td>
        <td><a href="https://i.redd.it/712a60hha4771.png"><img src="https://i.redd.it/712a60hha4771.png" alt="Item #3039"style={{"width":"80px", "height":"75px"}}></img></a><p><h5 style={{"color": "#000000", "font-family":"helvetica", "font-size":"14px", "text-align":"center"}}><p>#3039</p></h5></p></td>
        <td><a href="https://i.redd.it/p9ex8jxsa4771.png"><img src="https://i.redd.it/p9ex8jxsa4771.png" alt="Item #3041"style={{"width":"55px", "height":"95px"}}></img></a><p><h5 style={{"color": "#000000", "font-family":"helvetica", "font-size":"14px", "text-align":"center"}}><p>#3041</p></h5></p></td>
        <td><a href="https://i.redd.it/50agpvfib4771.png"><img src="https://i.redd.it/50agpvfib4771.png" alt="Item #3042"style={{"width":"55px", "height":"95px"}}></img></a><p><h5 style={{"color": "#000000", "font-family":"helvetica", "font-size":"14px", "text-align":"center"}}><p>#3042</p></h5></p></td>
        <td><a href="https://i.redd.it/8hufgnhjm9771.png"><img src="https://i.redd.it/8hufgnhjm9771.png" alt="Item #3043"style={{"width":"40px", "height":"95px"}}></img></a><p><h5 style={{"color": "#000000", "font-family":"helvetica", "font-size":"14px", "text-align":"center"}}><p>#3043</p></h5></p></td>
        <td><a href="https://i.redd.it/45ca3m09x9771.png"><img src="https://i.redd.it/45ca3m09x9771.png" alt="Item #3045"style={{"width":"60px", "height":"80px"}}></img></a><p><h5 style={{"color": "#000000", "font-family":"helvetica", "font-size":"14px", "text-align":"center"}}><p>#3045</p></h5></p></td>
        <td><a href="https://i.redd.it/ba6jfqhby9771.png"><img src="https://i.redd.it/ba6jfqhby9771.png" alt="Item #3046"style={{"width":"60px", "height":"95px"}}></img></a><p><h5 style={{"color": "#000000", "font-family":"helvetica", "font-size":"14px", "text-align":"center"}}><p>#3046</p></h5></p></td>
        <td><a href="https://i.redd.it/gzalz6y7z9771.png"><img src="https://i.redd.it/gzalz6y7z9771.png" alt="Item #3047"style={{"width":"50px", "height":"95px"}}></img></a><p><h5 style={{"color": "#000000", "font-family":"helvetica", "font-size":"14px", "text-align":"center"}}><p>#3047</p></h5></p></td>
        <td><a href="https://i.redd.it/fck28jvsz9771.png"><img src="https://i.redd.it/fck28jvsz9771.png" alt="Item #3048"style={{"width":"40px", "height":"10px"}}></img></a><p><h5 style={{"color": "#000000", "font-family":"helvetica", "font-size":"14px", "text-align":"center"}}><p>#3048</p></h5></p></td>
        <td><a href="https://i.redd.it/4bpx2xui0a771.png"><img src="https://i.redd.it/4bpx2xui0a771.png" alt="Item #3050"style={{"width":"70px", "height":"75px"}}></img></a><p><h5 style={{"color": "#000000", "font-family":"helvetica", "font-size":"14px", "text-align":"center"}}><p>#3050</p></h5></p></td>
        <td><a href="https://i.redd.it/yty638lc1a771.png"><img src="https://i.redd.it/yty638lc1a771.png" alt="Item #3051"style={{"width":"70px", "height":"60px"}}></img></a><p><h5 style={{"color": "#000000", "font-family":"helvetica", "font-size":"14px", "text-align":"center"}}><p>#3051</p></h5></p></td>
        <td><a href="https://i.redd.it/7hcl11cx1a771.png"><img src="https://i.redd.it/7hcl11cx1a771.png" alt="Item #3052"style={{"width":"40px", "height":"10px"}}></img></a><p><h5 style={{"color": "#000000", "font-family":"helvetica", "font-size":"14px", "text-align":"center"}}><p>#3052</p></h5></p></td>
        <td><a href="https://i.redd.it/y4md8ohf3a771.png"><img src="https://i.redd.it/y4md8ohf3a771.png" alt="Item #3053"style={{"width":"35px", "height":"10px"}}></img></a><p><h5 style={{"color": "#000000", "font-family":"helvetica", "font-size":"14px", "text-align":"center"}}><p>#3053</p></h5></p></td>
        <td><a href="https://i.redd.it/zavoldcx3a771.png"><img src="https://i.redd.it/zavoldcx3a771.png" alt="Item #3054"style={{"width":"70px", "height":"60px"}}></img></a><p><h5 style={{"color": "#000000", "font-family":"helvetica", "font-size":"14px", "text-align":"center"}}><p>#3054</p></h5></p></td>
        <td><a href="https://i.redd.it/n9b4iocr4a771.png"><img src="https://i.redd.it/n9b4iocr4a771.png" alt="Item #3055"style={{"width":"45px", "height":"10px"}}></img></a><p><h5 style={{"color": "#000000", "font-family":"helvetica", "font-size":"14px", "text-align":"center"}}><p>#3055</p></h5></p></td>
        <td><a href="https://i.redd.it/n1shbh3b5a771.png"><img src="https://i.redd.it/n1shbh3b5a771.png" alt="Item #3056"style={{"width":"40px", "height":"70px"}}></img></a><p><h5 style={{"color": "#000000", "font-family":"helvetica", "font-size":"14px", "text-align":"center"}}><p>#3056</p></h5></p></td>
        </tr>
    </table>

    <hr/>

    <p><h5 style={{"color":"#00a3cc","font-size":"20px","font-family":"Helvetica"}}><u>Small Bird Cages:</u></h5></p>
    <hr/>
    <p><h5 style={{"color":"#00a3cc","font-size":"20px","font-family":"Helvetica"}}><u>Large Bird Cages:</u></h5></p>
    <hr/>
    <p><h5 style={{"color":"#00a3cc","font-size":"20px","font-family":"Helvetica"}}><u>Bird Cage Stands:</u></h5></p>
    <hr/>
    <p><h5 style={{"color":"#00a3cc","font-size":"20px","font-family":"Helvetica"}}><u>Hamster Cages:</u></h5></p>
    <hr/>
    <p><h5 style={{"color":"#00a3cc","font-size":"20px","font-family":"Helvetica"}}><u>Nests and Others:</u></h5></p>


    <body style={{"background":"url(https://i.redd.it/t3b616ul9a671.png)"}}>
    </body>
    
  </div>
  )
  }
