import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'


export default function Home() {
  return (
    <div style={{"background":"url(https://i.redd.it/t3b616ul9a671.png)"}}>
      <Head>
        <title>O.T.E. Exotic</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      
    <h1 style={{"text-align":"center"}}>
        <u>
            <p style={{"font-size": "55px", "font-family":"Helvetica", "color":"#00a3cc", "padding-top":"50px", "padding-bottom":"50px"}}>O.T.E. EXOTIC CO.</p>
        </u>
    </h1>

    <h5 style={{"text-align":"center", "padding-bottom":"20px"}}>
        <p style={{"font-size": "20px", "color":"#000000", "font-family": "Helvetica", "padding-top":"20px"}}>
        <u> Wholesale Birds, Cages and Accessories</u>
        </p>
    </h5> 

    <hr/>
    <h4 style={{"text-align":"center", "font-family":"Helvetica",  "padding-top":"20px", "padding-bottom":"20px"}}>
      <ul><li><Link href="/"><a>Home</a></Link></li>
      <li><Link href="/catalog"><a>Catalog</a></Link></li>
      <li><Link href="/contact"><a>Contact Information</a></Link></li>
      </ul>
    </h4>

    <hr/>
    
    <div style={{"padding-left":'10px'}}>
    <p><h3 style={{"color":"#00a3cc", "font-size":"25px", "font-family":"helvetica", "padding-top":"40px"}}><u>Catalog</u></h3><h5 style={{"color":"#00a3cc", "font-size":"14", "font-family":"helvetica"}}>Want a closer look? Try clicking the pictures!</h5></p>
    <p><h5 style={{"color":"#00a3cc", "font-family":"helvetica", "font-size":"14", "padding-bottom":"40px"}}>(Some Items have multiple colors! Please contact Oscar if you have any questions!)</h5></p>

    <p><h5 style={{"color":"#00a3cc", "font-size":"20px", "font-family":"Helvetica"}}><u>Feeders:</u></h5></p>
    
    <table>
        <tr style={{"margin-left":"auto", "margin-right":"auto",}}>
        <td><Image src="/item8001.png" alt="Item  #8001" width={60} height={80}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8001</p></h5></p></td>
        <td><Image src="/item8002.png" alt="Item  #8002" width={60} height={80}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8002</p></h5></p></td>
        <td><Image src="/item8003.png" alt="Item  #8003" width={70} height={80}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8003</p></h5></p></td>
        <td><Image src="/item8004.png" alt="Item  #8004" width={65} height={80}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8004</p></h5></p></td>
        <td><Image src="/item8005.png" alt="Item  #8005" width={65} height={80}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8005</p></h5></p></td>
        <td><Image src="/item8006.png" alt="Item  #8006" width={60} height={80}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8006</p></h5></p></td>
        <td><Image src="/item8007.png" alt="Item  #8007" width={60} height={80}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8007</p></h5></p></td>
        <td><Image src="/item8021.png" alt="Item  #8021" width={50} height={80}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8021</p></h5></p></td>
        <td><Image src="/item8022.png" alt="Item  #8022" width={55} height={80}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8022</p></h5></p></td>
        <td><Image src="/item8023.png" alt="Item  #8023" width={70} height={60}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8023</p></h5></p></td>
        <td><Image src="/item8031.png" alt="Item  #8031" width={55} height={50}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8031</p></h5></p></td>
        <td><Image src="/item8032.png" alt="Item  #8032" width={60} height={65}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8032</p></h5></p></td>
        <td><Image src="/item8033.png" alt="Item  #8033" width={60} height={70}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8033</p></h5></p></td>
        <td><Image src="/item8035.png" alt="Item  #8035" width={60} height={70}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8035</p></h5></p></td>
        <td><Image src="/item8036.png" alt="Item  #8036" width={60} height={70}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8036</p></h5></p></td>
        <td><Image src="/item8037.png" alt="Item  #8037" width={65} height={70}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8037</p></h5></p></td>
        <td><Image src="/item8041.png" alt="Item  #8041" width={55} height={70}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8041</p></h5></p></td>
        <td><Image src="/item8050.png" alt="Item  #8050" width={80} height={70}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8050</p></h5></p></td>
        </tr>
        <tr>
        <td><Image src="/item8051.png" alt="Item  #8051" width={55} height={65}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8051</p></h5></p></td>
        <td><Image src="/item8052.png" alt="Item  #8052" width={60} height={70}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8052</p></h5></p></td>
        <td><Image src="/item8053.png" alt="Item  #8053" width={60} height={70}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8053</p></h5></p></td>
        <td><Image src="/item8053B.png" alt="Item  #8053B" width={60} height={65}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8053B</p></h5></p></td>
        <td><Image src="/item8054.png" alt="Item  #8054" width={60} height={65}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8054</p></h5></p></td>
        <td><Image src="/item8055.png" alt="Item  #8055" width={50} height={45}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8055</p></h5></p></td>
        <td><Image src="/item8058.png" alt="Item  #8058" width={60} height={55}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8058</p></h5></p></td>
        <td><Image src="/item8059.png" alt="Item  #8059" width={55} height={50}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8059</p></h5></p></td>
        <td><Image src="/item8097.png" alt="Item  #8097" width={50} height={70}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8097</p></h5></p></td>
        <td><Image src="/item8098.png" alt="Item  #8098" width={55} height={65}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8098</p></h5></p></td>
        <td><Image src="/item8062.png" alt="Item  #8062" width={60} height={60}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8062</p></h5></p></td>
        <td><Image src="/item8064.png" alt="Item  #8064" width={60} height={60}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8064</p></h5></p></td>
        <td><Image src="/item8065.png" alt="Item  #8065" width={60} height={60}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8065</p></h5></p></td>
        <td><Image src="/item8066.png" alt="Item  #8066" width={65} height={65}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8066</p></h5></p></td>
        <td><Image src="/item8067.png" alt="Item  #8067" width={65} height={65}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8067</p></h5></p></td>
        <td><Image src="/item8068.png" alt="Item  #8068" width={60} height={60}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8068</p></h5></p></td>
       </tr>
    </table>
    <table>
        <tr>
        <td><Image src="/item8081.png" alt="Item  #8081" width={40} height={70}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8081</p></h5></p></td>
        <td><Image src="/item8082.png" alt="Item  #8082" width={40} height={70}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8082</p></h5></p></td>
        <td><Image src="/item8084.png" alt="Item  #8084" width={35} height={65}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8084</p></h5></p></td>
        <td><Image src="/item8085.png" alt="Item  #8085" width={25} height={80}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8085</p></h5></p></td>
        <td><Image src="/item8038.png" alt="Item  #8038" width={120} height={70}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8038</p></h5></p></td>
        <td><Image src="/item00162.png" alt="Item  #00162" width={60} height={70}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#00162</p></h5></p></td>
        <td><Image src="/item00119.png" alt="Item  #00119" width={70} height={80}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#00119</p></h5></p></td>
        <td><Image src="/item00112.png" alt="Item  #00112" width={60} height={70}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#00112</p></h5></p></td>
        <td><Image src="/item00127.png" alt="Item  #00127" width={60} height={70}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#00127</p></h5></p></td>

        </tr>
    </table>
    <hr/>

    <p><h5 style={{"color":"#00a3cc", "font-size":"20px", "font-family":"Helvetica"}}><u>Toys and Accessories:</u></h5></p>

    <table>
        <tr>
        <td><Image src="/item8331.png" alt="Item  #8331" width={40} height={60}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8331</p></h5></p></td>
        <td><Image src="/item8334.png" alt="Item  #8334" width={65} height={70}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8334</p></h5></p></td>
        <td><Image src="/item8336.png" alt="Item  #8336" width={35} height={85}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8336</p></h5></p></td>
        <td><Image src="/item8338.png" alt="Item  #8338" width={40} height={90}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8338</p></h5></p></td>
        <td><Image src="/item8399.png" alt="Item  #8399" width={60} height={70}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8339</p></h5></p></td>
        <td><Image src="/item8095.png" alt="Item  #8095" width={60} height={70}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8095</p></h5></p></td>
        <td><Image src="/item8091.png" alt="Item  #8091" width={45} height={70}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8091</p></h5></p></td>
        <td><Image src="/item8201.png" alt="Item  #8201" width={60} height={70}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8201</p></h5></p></td>
        <td><Image src="/item8611.png" alt="Item  #8611" width={65} height={70}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8611</p></h5></p></td>
        <td><Image src="/item8613.png" alt="Item  #8613" width={65} height={70}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8613</p></h5></p></td>
        <td><Image src="/item8614.png" alt="Item  #8614" width={55} height={60}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8614</p></h5></p></td>
        <td><Image src="/item8615.png" alt="Item  #8615" width={60} height={70}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8615</p></h5></p></td>
        <td><Image src="/item8618.png" alt="Item  #8618" width={70} height={80}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8618</p></h5></p></td>
        <td><Image src="/item8502.png" alt="Item  #8502" width={38} height={45}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8502</p></h5></p></td>
        <td><Image src="/item8504.png" alt="Item  #8504" width={50} height={70}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8504</p></h5></p></td>
        <td><Image src="/item8506.png" alt="Item  #8506" width={65} height={80}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8506</p></h5></p></td>
        <td><Image src="/item8451.png" alt="Item  #8451" width={40} height={45}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8451</p></h5></p></td>
        <td><Image src="/item8452.png" alt="Item  #8452" width={40} height={45}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8452</p></h5></p></td>
        </tr>
    </table>

    <table style={{"padding-bottom":"40px"}}>
        <tr>
        <td><Image src="/item8542.png" alt="Item  #8542; Item #8543" width={120} height={40}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "12px", "text-align":"center"}}><p><b>#8542</b>:9.5''  <b>#8543</b>:12''</p></h5></p></td>
        <td><Image src="/item8544.png" alt="Item  #8544; Item #8545" width={152} height={40}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p><b>#8544</b>:18''  <b>#8545</b>:24''</p></h5></p></td>
        <td><Image src="/item8564.png" alt="Item  #8564" width={180} height={40}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8564:18''</p></h5></p></td>
        <td><Image src="/item8565.png" alt="Item  #8565" width={190} height={40}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p>#8565:24''</p></h5></p></td>
        <td><Image src="/item8546.png" alt="Item  #8546; Item #8547" width={180} height={40}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p><b>#8546</b>:36''  <b>#8547</b>:48''</p></h5></p></td>
        <td><Image src="/item8566.png" alt="Item  #8566; Item #8567" width={180} height={40}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p><b>#8566</b>:36''  <b>#8567</b>:48''</p></h5></p></td>
        </tr>
    </table>

    <table> 
        <tr>
        <td><Image src="/item8651.png" alt="Item  #8651; Item #8652; Item #8652; Item #8654; Item#8655;" width={180} height={80}></Image></td>
        <td>
        <h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "12px", "text-align": "center", "text-align":"left"}}>
        <p>#8651:Ø 6"×13"</p>
        <p>#8652:Ø 8"×20"</p>
        <p>#8653:Ø 9.5"×22"</p>
        <p>#8654:Ø 11"×29.5"</p>
        <p>#8655:Ø 11"×48"</p>
        </h5>
        </td>
        <td><Image src="/item8570.png" alt="Item  #8570;" width={80} height={15}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "12px", "text-align":"center"}}><p><b>#8570:7"</b></p></h5></p></td>
        <td><Image src="/item8577.png" alt="Item  #8577;" width={120} height={12}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "12px", "text-align":"center"}}><p><b>#8577:17"</b></p></h5></p></td>
        <td><Image src="/item8578.png" alt="Item  #8578;" width={129} height={12}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "12px", "text-align":"center"}}><p><b>#8578:18"</b></p></h5></p></td>
        <td><Image src="/item8571.png" alt="Item  #8571;" width={140} height={12}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "12px", "text-align":"center"}}><p><b>#8571:24"</b></p></h5></p></td>
        <td><Image src="/item8572.png" alt="Item  #8572;" width={145} height={12}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "12px", "text-align":"center"}}><p><b>#8572:31"</b></p></h5></p></td>
        </tr>
    </table>

    <table>
        <tr>
        <td><Image src="/item3062.png" alt="Item  #3062;" width={60} height={90}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p><b>#3062</b></p></h5></p></td>
        <td><Image src="/item3063.png" alt="Item  #3063;" width={60} height={90}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p><b>#3063</b></p></h5></p></td>
        <td><Image src="/item3064.pnh.png" alt="Item  #3064;" width={60} height={90}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size":"14px", "text-align":"center"}}><p><b>#3064</b></p></h5></p></td>
        <td><Image src="/item3065.png" alt="Item  #3065;" width={60} height={100}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p><b>#3065</b></p></h5></p></td>
        <td><Image src="/item3066.png" alt="Item  #3066;" width={60} height={100}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p><b>#3066</b></p></h5></p></td>
        <td><Image src="/item3091.png" alt="Item  #3091;" width={45} height={85}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p><b>#3091</b></p></h5></p></td>
        <td><Image src="/item3092.png" alt="Item  #3092;" width={40} height={110}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p><b>#3092</b></p></h5></p></td>
        <td><Image src="/item3093.png" alt="Item  #3093;" width={40} height={105}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p><b>#3093</b></p></h5></p></td>
        <td><Image src="/item3096.png" alt="Item  #3096;" width={60} height={70}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p><b>#3096</b></p></h5></p></td>
        <td><Image src="/item3097.png" alt="Item  #3097;" width={45} height={105}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p><b>#3097</b></p></h5></p></td>
        <td><Image src="/item3098.png" alt="Item  #3098;" width={50} height={105}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p><b>#3098</b></p></h5></p></td>
        <td><Image src="/item3011.png" alt="Item  #3011;" width={70} height={45}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p><b>#3011</b></p></h5></p></td>
        <td><Image src="/item3012.png" alt="Item  #3012;" width={70} height={50}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p><b>#3012</b></p></h5></p></td>
        <td><Image src="/item3013.png" alt="Item  #3013;" width={75} height={55}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p><b>#3013</b></p></h5></p></td>
        <td><Image src="/item3014.png" alt="Item  #3014;" width={80} height={60}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p><b>#3014</b></p></h5></p></td>
        <td><Image src="/item3021.png" alt="Item  #3021;" width={55} height={55}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p><b>#3021</b></p></h5></p></td>
        <td><Image src="/item3022.png" alt="Item  #3023;" width={60} height={60}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p><b>#3022</b></p></h5></p></td>
        <td><Image src="/item3023.png" alt="Item  #3023;" width={65} height={65}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p><b>#3023</b></p></h5></p></td>
        <td><Image src="/item3024.png" alt="Item  #3024;" width={70} height={70}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p><b>#3024</b></p></h5></p></td>
        </tr>
    </table>

    <table>
        <tr>
        <td><Image src="/item3031.png" alt="Item  #3031;" width={55} height={70}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p><b>#3031</b></p></h5></p></td>
        <td><Image src="/item3036.png" alt="Item  #3036;" width={55} height={70}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p><b>#3036</b></p></h5></p></td>
        <td><Image src="/item3037.png" alt="Item  #3037;" width={55} height={70}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p><b>#3037</b></p></h5></p></td>
        <td><Image src="/item3038.png" alt="Item  #3038;" width={55} height={75}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p><b>#3038</b></p></h5></p></td>
        <td><Image src="/item3039.png" alt="Item  #3039;" width={80} height={75}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p><b>#3039</b></p></h5></p></td>
        <td><Image src="/item3041.png" alt="Item  #3041;" width={55} height={95}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p><b>#3041</b></p></h5></p></td>
        <td><Image src="/item3042.png" alt="Item  #3042;" width={55} height={95}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p><b>#3042</b></p></h5></p></td>
        <td><Image src="/item3043.png" alt="Item  #3043;" width={40} height={95}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p><b>#3043</b></p></h5></p></td>
        <td><Image src="/item3045.png" alt="Item  #3045;" width={60} height={80}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p><b>#3045</b></p></h5></p></td>
        <td><Image src="/item3046.png" alt="Item  #3046;" width={60} height={95}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p><b>#3046</b></p></h5></p></td>
        <td><Image src="/item3047.png" alt="Item  #3047;" width={50} height={95}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p><b>#3047</b></p></h5></p></td>
        <td><Image src="/item3048.png" alt="Item  #3048;" width={40} height={100}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p><b>#3048</b></p></h5></p></td>
        <td><Image src="/item3050.png" alt="Item  #3050;" width={70} height={75}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p><b>#3050</b></p></h5></p></td>
        <td><Image src="/item3051.png" alt="Item  #3051;" width={70} height={60}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p><b>#3051</b></p></h5></p></td>
        <td><Image src="/item3052.png" alt="Item  #3052;" width={40} height={100}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p><b>#3052</b></p></h5></p></td>
        <td><Image src="/item3053.png" alt="Item  #3053;" width={35} height={100}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p><b>#3053</b></p></h5></p></td>
        <td><Image src="/item3054.png" alt="Item  #3054;" width={30} height={100}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p><b>#3054</b></p></h5></p></td>
        <td><Image src="/item3055.png" alt="Item  #3055;" width={45} height={100}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p><b>#3055</b></p></h5></p></td>
        <td><Image src="/item3056.png" alt="Item  #3056;" width={40} height={70}></Image><p><h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "14px", "text-align":"center"}}><p><b>#3056</b></p></h5></p></td>
        </tr>
    </table>

    <table>
        <tr>
        <td><Image src="/item8634.png" alt="Item  #8634; Item #8635; Item #8633; Item #8636;" width={100} height={90}></Image></td>
        <td>
        <h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "12px", "text-align": "center", "text-align":"left"}}>
        <p>#8633:Black</p>
        <p>#8634:White</p>
        <p>#8635:Purple</p>
        <p>#8636:Blue"</p>
        <p>24"x16"</p>
        </h5>
        </td>
        <td><Image src="/item8644.png" alt="Item  #8644; Item #8643;" width={110} height={100}></Image></td>
        <td>
        <h5 style={{"color": "#000000", "font-family": "helvetica", "font-size": "12px", "text-align": "center", "text-align":"left"}}>
        <p>#8643:Black</p>
        <p>#8644:White</p>
        <p>30"x18"</p> </h5>
        </td>
        </tr>
    </table>
    <hr/>

    <p><h5 style={{"color":"#00a3cc","font-size":"20px","font-family":"Helvetica"}}><u>Small Bird Cages:</u></h5></p>

    <hr/>
    <p><h5 style={{"color":"#00a3cc","font-size":"20px","font-family":"Helvetica"}}><u>Large Bird Cages:</u></h5></p>
    <hr/>
    <p><h5 style={{"color":"#00a3cc","font-size":"20px","font-family":"Helvetica"}}><u>Bird Cage Stands:</u></h5></p>
    <hr/>
    <p><h5 style={{"color":"#00a3cc","font-size":"20px","font-family":"Helvetica"}}><u>Hamster Cages:</u></h5></p>
    <hr/>
    <p><h5 style={{"color":"#00a3cc","font-size":"20px","font-family":"Helvetica"}}><u>Nests, Carriers, and Others:</u></h5></p>
  </div>
  </div>
  )
  }
