import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div style={{"background":"url(https://i.redd.it/au40rxdxbo571.png)"}}>
      <Head>
        <title>O.T.E. Exotic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 style={{"text-align":"center"}}>
      <u>
      <p style={{"font-size": "55px", "font-family":"Helvetica", "color": "#00a3cc", "padding-top":"50px", "padding-bottom":"50px"}}>O.T.E. EXOTIC CO.</p>
      </u>
      </h1>
      <h5 style={{"text-align":"center", "padding-bottom":"20px"}}>
      <p style={{"font-size": "20px", "color":"#000000", "font-family": "Helvetica", "padding-top":"20px"}}>
      <u> Wholesale Birds, Cages and Accessories</u>
     </p>
      </h5>
      <hr/>
    <h4 style={{"text-align":"center", "font-family":"Helvetica", "padding-top":"20px", "padding-bottom":"20px"}}>
      <ul><li><Link href="/"><a>Home</a></Link></li>
      <li><Link href="/catalog"><a>Catalog</a></Link></li>
      <li><Link href="/contact"><a>Contact Information</a></Link></li>
      </ul>
    </h4>

    <hr/>
    <div style={{"padding-left":"10px"}}>
      <p><h4 style={{"font-size":"30px", "color":"#00a3cc", "font-family":"Helvetica", "padding-top":"40px"}}>Hello I'm Oscar.</h4>
          <h4 style={{"font-size":"20px", "color":"#FFFFFF", "font-family":"Helvetica"}}>I am the owner of O.T.E. Exotic Co. where I wholesale cages and<br/> accessories.<br/></h4> 
          <h4 style={{"font-size":"30px", "color":"#00a3cc", "font-family":"Helvetica", "padding-top":"40px"}}><u>You can reach me at:</u></h4>
          <h4 style={{"font-size":"20px", "color":"#FFFFFF", "font-family":"Helvetica"}}>(626) 321-0910 via text<br/>or<br/>oscartran2002@yahoo.com via email</h4>
          <br/><h4 style={{"font-family":"Helvetica","font-size":"20px","color":"#FFFFFF","text-align":"center", "padding-top":"100px", "padding-bottom":"150px"}}> Please contact me if you have any further questions!</h4>
      </p>
      </div>
    </div>

  )
}
