import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'


export default function Home() {
  return (
    <div style={{"background": "url(https://i.redd.it/t3b616ul9a671.png)"}}>
      <Head>
        <title>O.T.E. Exotic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <h1 style={{"text-align":"center"}}>
        <u>
        <p style={{"font-size": "55px", "font-family":"Helvetica", "color": "#00a3cc", "padding-top":"50px", "padding-bottom":"50px"}}>O.T.E. EXOTIC CO.</p>
        </u>
      </h1>

      <h5 style={{"text-align":"center", "padding-bottom":"20px"}}>
        <p style={{"font-size": "20px", "color":"#000000", "font-family": "Helvetica", "padding-top":"20px"}}>
          <u> Wholesale Birds, Cages and Accessories</u>
        </p>
      </h5>

      <hr/>

      <h4 style={{"text-align":"center", "font-family":"Helvetica", "padding-top":"20px", "padding-bottom":'20px'}}>
      <ul><li><Link href="/"><a>Home</a></Link></li>
      <li><Link href="/catalog"><a>Catalog</a></Link></li>
      <li><Link href="/contact"><a>Contact Information</a></Link></li>
      </ul>
      </h4>

      <hr/>
      <h3 style={{"font-family":"helvetica","text-align":"left","font-size":"30px","color":"#00a3cc", "padding-top":"40px", "padding-left":"10px"}}>
        <u>
        Best Sellers!
        </u>
      </h3>
      <div style={{"background": "url(https://i.redd.it/t3b616ul9a671.png)", "padding-bottom":"550px", "padding-top":"40px"}}>
        <ul2 style={{"list-style-type":"none"}}>

        <h3 style={{"text-align":"center", "background": "url(https://i.redd.it/t3b616ul9a671.png)"}}>
        <li style={{"padding":"12px", "background": "url(https://i.redd.it/t3b616ul9a671.png)"}}>
            <Image width={250} height={350} src="/item3373.png"  alt="Item  #3373"></Image>
            <h5 style={{"color": "#000000","font-family": "helvetica","font-size": "20px"}}><p>#3374</p></h5>
        </li>

        <li style={{"padding":"12px", "background": "url(https://i.redd.it/t3b616ul9a671.png)"}}>
            <Image width={300} height={300} src="/item2424.png"  alt="Item  #2424"></Image>
            <h5 style={{"color": "#000000","font-family": "helvetica","font-size": "20px"}}><p>#2424</p></h5>
        </li>

        <li style={{"padding":"12px", "background": "url(https://i.redd.it/t3b616ul9a671.png)"}}>
            <Image width={300} height={200} src="/item8242.png"  alt="Item  #8242"></Image>
            <h5 style={{"color": "#000000","font-family": "helvetica","font-size": "20px"}}><p>#8242</p></h5>
        </li>

        <li style={{"padding":"12px", "background": "url(https://i.redd.it/t3b616ul9a671.png)"}}>
            <Image width={250} height={350} src="/item0482.png"  alt="Item  #0482"></Image>
            <h5 style={{"color": "#000000","font-family": "helvetica","font-size": "20px"}}><p>#0482</p></h5>
        </li>
        </h3>
      </ul2>
      </div>
  
  
  </div>
  )
  }
