import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>O.T.E. Exotic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {/* <h1 style={{"text-align":"center"}}>
        <u>
        <p style={{"font-size": "55px", "font-family":"Helvetica", "color": "#00a3cc"}}>O.T.E. EXOTIC CO.</p>
        </u>
      </h1>

      <h5 style={{"text-align":"center"}}>
        <p style={{"font-size": "30px", "color":"#000000", "font-family": "Helvetica"}}>
          <u> Wholesale Birds, Cages and Accessories</u>
        </p>
      </h5>

      <hr/>

      <h4 style={{"text-align":"center", "font-family":"Helvetica"}}>
      <ul><li><a href="/">Home</a></li>
      <li><a href="/catalog">Catalog</a></li>
      <li><a href="/contact">Contact Information</a></li>
      </ul>
      </h4>

      <hr/>
      <h3 style={{"font-family":"helvetica","text-align":"left","font-size":"30px","color":"#00a3cc"}}>
        <u>
        Best Sellers!
        </u>
      </h3>
      <ul2 style={{"list-style-type":"none"}}>

      <h3 style={{"text-align":"center"}}>
      <li><a href="https://i.redd.it/zw37vsrsio571.png"><img src="https://i.redd.it/zw37vsrsio571.png" alt="Item  #3373"style={{"width":"250px","height":"350px"}}/></a>
      <h5 style={{"color": "#000000","font-family": "helvetica","font-size": "20px"}}><p>#3373</p></h5></li>

      <li><a href="https://i.redd.it/af7mwf2ddo571.png"><img src="https://i.redd.it/af7mwf2ddo571.png" alt="Item #2424" style={{"width":"300px", "height":"300px"}}/></a>
      <h5 style={{"color": "#000000","font-family": "helvetica","font-size": "20px"}}><p>#2424</p></h5></li>

      <li><a href="https://i.redd.it/az3u9zdwho571.png"><img src="https://i.redd.it/az3u9zdwho571.png" alt="Item #8242" style={{"width":"300px", "height":"200px"}}/></a>
      <h5 style={{"color": "#000000","font-family": "helvetica","font-size": "20px"}}><p>#8242</p></h5></li>

      <li><a href="https://i.redd.it/0ais0spxgo571.png"><img src="https://i.redd.it/0ais0spxgo571.png" alt="Item  #0482"style={{"width":"250px", "height":"350px"}}/></a>
      <h5 style={{"color": "#000000","font-family": "helvetica","font-size": "20px"}}><p>#0482</p></h5></li>

      </h3>
      </ul2>

      <body style={{"background": "url(https://i.redd.it/t3b616ul9a671.png)"}}>

      </body>     */}
  </div>
  )
  }
